### ISSUE TITLE
ImportError: No module named

### ISSUE THREAD

**Issue by saun4app** [hbetts/generator-python-lib#3]
Adding `import requests` to `utils.py` produced the following error
`ImportError: No module named 'requests'` when running `python setup.py test` (see below).

Before adding `import requests` the test was `OK`. The same problem occurs with other packages as well.  

Please let me know what I what need to do to resolve this problem.  Thank you very much.

```bash
py34 inst-nodeps: /home/vagrant/Dropbox/code-work/pylib/.tox/dist/pylib-1.0.0.zip
py34 runtests: PYTHONHASHSEED='2137819445'
py34 runtests: commands[0] | python -m unittest
E
======================================================================
ERROR: tests.test_utils (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/usr/lib/python3.4/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: tests.test_utils
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.4/unittest/loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "/home/vagrant/Dropbox/code-work/pylib/tests/test_utils.py", line 6, in <module>
    from pylib.utils import Constants, orbital_speed, circumference, orbital_period
  File "/home/vagrant/Dropbox/code-work/pylib/pylib/utils.py", line 6, in <module>
    import requests
ImportError: No module named 'requests'
```

**Comment by saun4app** [comment]
I stumbled into this:  running `python setup.py test` caused the `ImportError: No module named` problem. However, running `tox` works.

**Comment by hbetts** [comment]
@saun4app I apologize that the instructions in the `README.md` file did not provide any guidance on how to manage dependencies.

I've added a section called [Adding Dependencies](https://github.com/hbetts/generator-python-lib#adding-dependencies) that describes how dependencies should be added to the `install_requires` list in `setup.py`. 

For your situation, please add `requests` to the `install_requires` list in your scaffolded project's `install_requires` list.

At that point you should be able to run `python setup.py test`, and the `requests` package will be installed into each test environment.

I've also updated the `tox.ini` template file to instruct `tox` to re-create each test environment every time you run `tox`. This will slow down test setup a little, but it will ensure that any new dependencies declared in `setup.py` are properly installed.

If you encounter any further issues with the test environments, or would like further clarification in the `README.md` file, please file a new issue, and I'll take a look at what I can do.

**Comment by saun4app** [comment]
@hbetts <https://github.com/hbetts>, thank you for being so responsive.  I
am fairly sure that before I submitted this issue, I tried adding
requests package
in  setup.py install_requires list.  At the moment, I am not able to verify
the revised version of python-lib because I am not able to get pass CI
Provider installation step.  I have submitted new issue.
