### ISSUE TITLE
Your CI provider option is not responsive to pressing enter key

### ISSUE THREAD

**Issue by saun4app** [hbetts/generator-python-lib#4]
@hbetts, 

I installing the most recent version of python-lib by running`sudo npm install -g yo` and  `sudo npm install -g generator-python-lib` the `Your CI provider` option is not responsive to pressing the `enter` key, therefore, not able to continue with the installation process.

**Comment by hbetts** [comment]
@saun4app thank you for reporting the issue.

Seems my validator code was incorrect and would only work for the default option (_Node_).

Therefore you couldn't select the Travis CI option (actually you could, and the validation function would be called as expected, but the library that handles prompting is hanging when it receives the validation response).

I've released 1.6.2 with a fix: https://github.com/hbetts/generator-python-lib/releases/tag/v1.6.2

I'll follow up separately with the underlying library to figure out why that's hanging.

**Comment by hbetts** [comment]
Also, I meant to highly recommend you don't install npm packages globally using `sudo`.

npm packages may specify life-cycle scripts that can be executed with the permissions you provide. This is a known security issue of npm: http://blog.npmjs.org/post/141702881055/package-install-scripts-vulnerability

**Comment by saun4app** [comment]
It works!  Thank you for your advice to avoid using `sudo` for `npm`.
