### ISSUE TITLE
Tox optional

### ISSUE THREAD

**Issue by saun4app** [hbetts/generator-python-lib#7]
@hbetts, I would like to suggest making Tox optional.  Tox and virtualenv are not very happy together lately.  People who don't care about supporting multiple python version can bypass tox.  Also, when tox works, it take a long time to run it.  Thank you.

**Comment by hbetts** [comment]
@saun4app I do tend to see projects call their unit test framework from `python setup.py test` rather than `tox`, and then call `tox` when they want to run `python setup.py test` from within different virtual environments.

I would be fine with the change.

**Comment by saun4app** [comment]
@hbetts,  thank you for being so responsive.  

I have setup a fresh ubuntu 16.04 Vritualbox, following the seteps in https://github.com/hbetts/generator-python-lib#readme, except using --always-copy to create venv.   Otherwise venv does not work.

`$ virtualenv --python=python3 venv  --always-copy`

Running 

`python setup.py test` 

with Coverage works ('test': Tox is commended out).   

Running 

`python setup.py test` 

with Tox produces this message:  ERROR: InvocationError: /usr/bin/python -m virtualenv --python /usr/bin/python3.

In any case, it would be nice to be able to turn Tox off because it takes a long time to run test with tox.

**Comment by hbetts** [comment]
@saun4app I've released version [2.0.0 of the generator](https://gitlab.com/hutson/generator-python-lib/commit/73bfe2ab9ad09b6d39935e42e7e87eab4875fbd7) that makes `python setup.py test` run the tests once using the version of Python installed in your virtual environment.

To run `tox` you'll need to invoke `tox` directly.

Please feel free to upgrade your projects using the newer version of the generator.

Also, please let me know if this meets your needs.

Lastly, I've moved my project to GitLab: https://gitlab.com/hutson/generator-python-lib

I've copied these issues over to GitLab, and will be closing out the GItHub issues in time.
